/**
 * Created by sabir on 28.11.16.
 */

//users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH_SUCCESS'
export const INITIALIZE_AUTH_FAIL = 'INITIALIZE_AUTH_FAIL'


//sessions
export const LOAD_USER_SESSIONS = 'LOAD_USER_SESSIONS'
export const LOAD_USER_SESSIONS_SUCCESS = 'LOAD_USER_SESSIONS_SUCCESS'
export const LOAD_USER_SESSIONS_FAIL = 'LOAD_USER_SESSIONS_FAIL'

export const LOAD_SESSION_DATA = 'LOAD_SESSION_DATA'
export const LOAD_SESSION_DATA_SUCCESS = 'LOAD_SESSION_DATA_SUCCESS'
export const LOAD_SESSION_DATA_FAIL = 'LOAD_SESSION_DATA_FAIL'

//pusher
export const PUSHER_MESSAGE_RECEIVED = 'PUSHER_MESSAGE_RECEIVED'
